apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-dns-operator-health
  namespace: dns-governance-policies
  annotations:
    policy.open-cluster-management.io/standards: NIST SP 800-53
    policy.open-cluster-management.io/categories: CM Configuration Management
    policy.open-cluster-management.io/controls: CM-2 Baseline Configuration
spec:
  remediationAction: inform
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: dns-operator-not-degraded
        spec:
          remediationAction: inform
          severity: critical
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: config.openshift.io/v1
                kind: ClusterOperator
                metadata:
                  name: dns
                status:
                  conditions:
                    - type: Degraded
                      status: "False"
                    - type: Available
                      status: "True"
